<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/some.proto

namespace HardGo\App\Some\V1\GPBMetadata;

class Some
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
ë
v1/some.protosome.v1"
Request
message (	"
Response
message (	2K
Reverse@
Do.some.v1.Request.some.v1.Response"Ç”‰ì/blocking/fasBiZ1gitlab.com/nuzfunzon/hard-go/pkg/protobuf/v1/some HardGo\\App\\Some\\V1‚HardGo\\App\\Some\\V1\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

